CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created TIMESTAMP,
    modified TIMESTAMP
);

CREATE TABLE images (
	id SERIAL PRIMARY KEY,
	path VARCHAR(300) NOT NULL UNIQUE,
	height INTEGER NOT NULL,
	width INTEGER NOT NULL,
	created TIMESTAMP,
    modified TIMESTAMP
);